# Server Information
address: localhost
port: 8000

# List of all the split files accessible to the server
splits:
  My Splits: splits.lss

# Name of the default split file to load
default_splits: My Splits

# Activate Global Hotkeys
hotkeys: true

# Layout Configuration
# Each Component is optional and can come in any order
layout:
  # -
  #   Title

  -
    Timer

  -
    Splits:
      visual_split_count: 5
      split_preview_count: 1
      always_show_last_split: true
      separator_last_split: true

  # -
  #   PreviousSegment

  # -
  #   PossibleTimeSave

  # -
  #   SumOfBest

  # -
  #   Graph:
  #     live_graph: true

  # -
  #   Text:
  #     text:
  #       Center: Some random text
