# Server Information
address: localhost
port: 8000

# Location of the Splits File
splits: splits.lss

# Activate Global Hotkeys
hotkeys: true

# Layout Configuration
# Each Component is optional and can come in any order
layout:
  -
    Title

  -
    Timer

  -
    Splits:
      visual_split_count: 5
      split_preview_count: 1
      always_show_last_split: true
      separator_last_split: true

  -
    PreviousSegment

  -
    PossibleTimeSave

  # -
  #   SumOfBest

  # -
  #   Graph:
  #     live_graph: true

  # -
  #   Text:
  #     text:
  #       Center: Some random text
